product:
  name: Red Hat Fuse
  abbreviation: Fuse-and-FIS
  stage: ${build.milestone}
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: ${version.fuse.prefix}
milestone: ${build.milestone}
group: Red Hat Fuse - Base ${version.fuse.project} ${build.milestone}
defaultBuildParameters:
  environmentId: 8
  buildScript: 'mvn -e -V -B -Dmaven.test.skip=true -DfailIfNoTests=false -Dtest=false clean
    deploy '

builds:
- name: karaf-4.2.9-${version.fuse.prefix}
  project: jboss-fuse/karaf
    #fetchScmUrl: ${karaf.fetch.scmUrl}
    #pushScmUrl: ${karaf.push.scmUrl}
    #tag: karaf-${version.karaf}
    #buildCommand: ${karaf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/karaf.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/karaf.git
  scmRevision: karaf-${version.karaf}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  alignmentParameters:
    - ${karaf.pme.options}

- name: cxf-xjc-utils-3.3.1-${version.fuse.prefix}
  project: jboss-fuse/cxf-xjc-utils
    #fetchScmUrl: ${cxf-xjc-utils.fetch.scmUrl}
    #pushScmUrl: ${cxf-xjc-utils.push.scmUrl}
    #tag: cxf-xjc-utils-${version.cxf.xjc-utils}
    #buildCommand: ${cxf-xjc-utils.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf-xjc-utils.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/cxf-xjc-utils.git
  buildScript: >
    mvn -e -V -B -Dmaven.test.skip=true -DfailIfNoTests=false -Dtest=false
    -Dcheckstyle.skip=true dependency:tree clean deploy
  scmRevision: cxf-xjc-utils-${version.cxf.xjc-utils}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  alignmentParameters:
    - ${cxf-xjc-utils.pme.options}

- name: swagger-core-1.5.24-${version.fuse.prefix}
  project: jboss-fuse/swagger-core
    #fetchScmUrl: ${swagger-core.fetch.scmUrl}
    #pushScmUrl: ${swagger-core.push.scmUrl}
    #tag: swagger-core-v2-${version.io.swagger.core.v2}
    #buildCommand: ${swagger-core.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/swagger-core.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/swagger-core.git
  buildScript: >
    mvn -e -V -B -Dmaven.test.skip.exec=true -Denforcer.skip=true
    -Dcheckstyle.skip=true dependency:tree clean deploy
  scmRevision: swagger-core-v2-${version.io.swagger.core.v2}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  alignmentParameters:
    - ${swagger-core.pme.options}

- name: swagger-core-2.1.3-${version.fuse.prefix}
  project: jboss-fuse/swagger-core
    #fetchScmUrl: ${swagger-core.fetch.scmUrl}
    #pushScmUrl: ${swagger-core.push.scmUrl}
    #tag: swagger-core-v3-${version.io.swagger.core.v3}
    #buildCommand: ${swagger-core.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/swagger-core.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/swagger-core.git
  buildScript: >
    mvn -e -V -B -Dmaven.test.skip.exec=true -Denforcer.skip=true
    -Dcheckstyle.skip=true  dependency:tree clean deploy
  scmRevision: swagger-core-v3-${version.io.swagger.core.v3}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  alignmentParameters:
    - ${swagger-core.pme.options}

- name: docker-maven-plugin-0.31.0-${version.fuse.prefix}
  project: jboss-fuse/docker-maven-plugin
    #fetchScmUrl: ${docker-maven-plugin.fetch.scmUrl}
    #pushScmUrl: ${docker-maven-plugin.push.scmUrl}
    #tag: docker-maven-plugin-${docker.maven.plugin.version}
    #buildCommand: ${docker-maven-plugin.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/docker-maven-plugin.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/docker-maven-plugin.git
  scmRevision: docker-maven-plugin-${docker.maven.plugin.version}
  alignmentParameters:
    - ${docker-maven-plugin.pme.options}
  buildScript: 'mvn -e -V -B -Dmaven.test.skip=true -DfailIfNoTests=false -Dtest=false -Dgpg.skip=true dependency:tree -Prelease clean deploy'

- name: kubernetes-client-4.6.2-${version.fuse.prefix}
  project: jboss-fuse/kubernetes-client
    #fetchScmUrl: ${kubernetes-client.fetch.scmUrl}
    #pushScmUrl: ${kubernetes-client.push.scmUrl}
    #tag: kubernetes-client-${version.kubernetes.client}
    #buildCommand: ${kubernetes-client.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/kubernetes-client.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/kubernetes-client.git
  buildScript: 'mvn -e -V -B -Dmaven.test.skip.exec=true -DfailIfNoTests=false -Dtest=false  dependency:tree clean deploy'
  scmRevision: kubernetes-client-${version.kubernetes.client}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  customPmeParameters:
    - ${kubernetes-client.pme.options}

- name: arquillian-cube-1.18.2-${version.fuse.prefix}
  project: jboss-fuse/arquillian-cube
    #fetchScmUrl: ${arquillian-cube.fetch.scmUrl}
    #pushScmUrl: ${arquillian-cube.push.scmUrl}
    #tag: arquillian-cube-${version.arquillian-cube}
    #buildCommand: ${arquillian-cube.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/arquillian-cube.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/arquillian-cube.git
  buildScript: 'mvn -e -V -B -Dmaven.test.skip.exec=true -DfailIfNoTests=false -Dtest=false dependency:tree clean deploy'
  scmRevision: arquillian-cube-${version.arquillian-cube}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  customPmeParameters:
    - ${arquillian-cube.pme.options}

outputPrefixes:
  releaseFile: fuse-test
  releaseDir: fuse-test
flow:
  licensesGeneration:
    strategy: GENERATE

  repositoryGeneration:
    strategy: BUILD_GROUP
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
addons:
  notYetAlignedFromDependencyTree: