product:
  name: Red Hat Fuse
  abbreviation: Fuse-and-FIS
  stage: ${build.milestone}
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: ${version.fuse.prefix}
milestone: ${build.milestone}
group: Red Hat Fuse - Base ${version.fuse.project} ${build.milestone}
defaultBuildParameters:
  environmentId: 8
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false clean
    deploy'

builds:
- name: cxf-3.3.3-${version.fuse.prefix}
  project: jboss-fuse/cxf
    #fetchScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #pushScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #tag: cxf-${version.cxf}
    #buildCommand: ${cxf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/cxf.git
  scmRevision: cxf-${version.cxf}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  customPmeParameters:
    - ${cxf.pme.options}
  buildPodMemory: 8
  buildScript: >
    mvn -e -V -B -DskipTests -Dtar.long.file.mode=posix -DfailIfNoTests=false -Dtest=false -Dcxf.public.suffix.list.url=http://dev138.mw.lab.eng.bos.redhat.com/miscellaneous/effective_tld_names.dat -Pdeploy clean deploy

- name: camel-3.0.0-${version.fuse.prefix}
  project: jboss-fuse/camel
    #fetchScmUrl: ${camel.fetch.scmUrl}
    #pushScmUrl: ${camel.push.scmUrl}
    #tag: camel-${version.camel}
    #buildCommand: ${camel.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/camel.git
  scmRevision: camel-${version.camel}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  buildPodMemory: 12
  buildScript: >
    export JAVA_TOOL_OPTIONS=\"-Xmx3g\"

    export MAVEN_OPTS=\"-Xmx4g\"

    mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Penable-schemagen,release,apt
    clean deploy -DkeepStagingRepositoryOnCloseRuleFailure=true -Dgpg.skip=true -pl
    '!org.apache.camel:camel-itest,!org.apache.camel.example:camel-example-swagger-xml'
  customPmeParameters:
    - ${camel.pme.options}
  extraRepositories:
    - http://resources.knopflerfish.org/repo/maven2/release/
  dependencies:
  - cxf-3.3.3-${version.fuse.prefix}

- name: camel-kafka-connector-0.0.1-${version.fuse.prefix}
    #fetchScmUrl: ${camel-kafka-connector.fetch.scmUrl}
    #pushScmUrl: ${camel-kafka-connector.push.scmUrl}
    #tag: camel-kafka-connector-${version.camel-kafka-connector}
    #buildCommand: ${camel-kafka-connector.buildCommand}
  project: jboss-fuse/camel-kafka-connector
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel-kafka-connector.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/camel-kafka-connector.git
  scmRevision: camel-kafka-connector-${version.camel-kafka-connector}
  buildScript: 'mvn -B clean deploy -DskipTests'
  customPmeParameters:
    - ${camel-kafka-connector.pme.options}
  dependencies:
    - camel-3.0.0-${version.fuse.prefix}

- name: camel-k-runtime-1.0.0-${version.fuse.prefix}
    #fetchScmUrl: ${camel-k-runtime.fetch.scmUrl}
    #pushScmUrl: ${camel-k-runtime.push.scmUrl}
    #tag: camel-k-runtime-${version.camel-k-runtime}
    #buildCommand: ${camel-k-runtime.buildCommand}
  project: jboss-fuse/camel-k-runtime
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel-k-runtime.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/camel-k-runtime.git
  scmRevision: camel-k-runtime-${version.camel-k-runtime}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  buildScript: 'mvn -e -V -B -DskipTests -Dgpg.skip=true -DfailIfNoTests=false -Prelease -Dtest=false clean deploy -DskipClean'
  customPmeParameters:
    - ${camel-k-runtime.pme.options}
  dependencies:
    - camel-3.0.0-${version.fuse.prefix}

- name: camel-quarkus-0.3.2-${version.fuse.prefix}
    #fetchScmUrl: ${camel-quarkus.fetch.scmUrl}
    #pushScmUrl: ${camel-quarkus.push.scmUrl}
    #tag: camel-quarkus-${version.camel-quarkus}
    #buildCommand: ${camel-quarkus.buildCommand}
  project: jboss-fuse/camel-quarkus
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel-quarkus.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/camel-quarkus.git
  scmRevision: camel-quarkus-${version.camel-quarkus}
  buildScript: 'mvn -B clean deploy -DskipTests'
  customPmeParameters:
    - ${camel-quarkus.pme.options}
  dependencies:
    - camel-3.0.0-${version.fuse.prefix}

outputPrefixes:
  releaseFile: fuse-test
  releaseDir: fuse-test
flow:
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
