product:
  name: Red Hat Fuse
  abbreviation: Fuse-and-FIS
  stage: EA1
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: ${version.fuse.prefix}
milestone: Sprint30
group: Fuse Standalone and FIS 7.2
defaultBuildParameters:
  environmentId: 1
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false clean
    deploy'

builds:
- name: karaf-4.2.0-${version.fuse.prefix}
  project: jboss-fuse/karaf
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/karaf.git
    #internalScmUrl: ${karaf.scmUrl}
    #tag: ${karaf.tag}
    #buildCommand: ${karaf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/karaf.git
  scmRevision: karaf-${version.karaf}
  customPmeParameters:
  - '-DdependencyOverride.com.sun.xml.bind:*@*=2.2.11.redhat-4'
  - '-DdependencyOverride.org.ow2.asm:*@*='
  - '-DprojectMetaSkip=true'

- name: cxf-3.1.11-${version.fuse.prefix}
  project: jboss-fuse/cxf
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/cxf.git
    #internalScmUrl: ${cxf.scmUrl}
    #tag: ${cxf.tag}
    #buildCommand: ${cxf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf.git
  scmRevision: cxf-${version.cxf}
  customPmeParameters:
    - '-DdependencyOverride.org.codehaus.woodstox:*@*='
    - '-DdependencyOverride.org.apache.abdera:*@*='
    - '-DdependencyOverride.javax.annotation:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.module:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.jaxrs:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.core:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.jaxrs:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.dataformat:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.datatype:*@*='
    - '-DprojectMetaSkip=true'
  buildScript: 'mvn  -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Dcxf.public.suffix.list.url=http://dev138.mw.lab.eng.bos.redhat.com/miscellaneous/effective_tld_names.dat
    -Pdeploy clean deploy'
  dependencies:
  - cxf-xjc-utils-3.1.1-${version.fuse.prefix}
  - karaf-4.2.0-${version.fuse.prefix}

- name: camel-2.21.0-${version.fuse.prefix}
  project: jboss-fuse/camel
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${camel.scmUrl}
    #tag: ${camel.tag}
    #buildCommand: ${camel.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel.git
  scmRevision: camel-${version.camel}
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Penable-schemagen,release,apt
    clean deploy -DkeepStagingRepositoryOnCloseRuleFailure=true -Dgpg.skip=true -pl
    !org.apache.camel:camel-itest,!org.apache.camel.example:camel-example-swagger-xml'
  customPmeParameters:
    - '-DprojectMetaSkip=true'
    - '-DdependencyExclusion.io.vertx:*@*=3.5.1.redhat-004'
    - '-DdependencyExclusion.com.fasterxml.jackson.dataformat:*@*=' 
    - '-DdependencyExclusion.com.fasterxml.jackson.datatype:*@*=' 
    - '-DdependencyExclusion.com.fasterxml.jackson.core:*@*='
    - '-DdependencyExclusion.com.fasterxml.jackson.jaxrs:*@*=' 
    - '-DdependencyExclusion.com.fasterxml.jackson.module:*@*=' 
    - '-DdependencyExclusion.com.sun.xml.bind:*@*=2.2.11.redhat-4'
    - '-DdependencyExclusion.com.github.everit-org.json-schema:*@*=1.6.0.redhat-1'
    - '-DdependencyExclusion.org.codehaus.woodstox:*@*='
    - '-DdependencyExclusion.org.apache.abdera:*@*='
    - '-DdependencyExclusion.org.reactivestreams:*@*='
  dependencies:
  - cxf-3.1.11-${version.fuse.prefix}
  - karaf-4.2.0-${version.fuse.prefix}

- name: camel-extra-2.21.0-${version.fuse.prefix}
  project: jboss-fuse/camel-extra
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${camel-extra.scmUrl}
    #tag: ${camel-extra.tag}
    #buildCommand: ${camel-extra.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel-extra.git
  scmRevision: camel-extra-${version.camel.extra}
  dependencies:
  - camel-2.21.0-${version.fuse.prefix}

- name: wsdl2rest-0.7.0-${version.fuse.prefix}
  project: jboss-fuse/wsdl2rest
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${wsdl2rest.scmUrl}
    #tag: ${wsdl2rest.tag}
    #buildCommand: ${wsdl2rest.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/wdl2rest.git
  scmRevision: wsdl2rest-${version.wsdl2rest}
  dependencies:
  - camel-2.21.0-${version.fuse.prefix}

- name: fuse-components-${version.fuse.prefix}
  project: jboss-fuse/fuse-components
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internatlScmUrl: ${fuse-components.scmUrl}
    #tag: ${fuse-components.tag}
    #buildCommand: ${fuse-components.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/fuse-components.git
  scmRevision: fuse-components-${version.fusesource.camel.sap}
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Prelease,all,enable-schemagen,deploy,ts.all,jaxws22,nochecks,sap,quickstarts,apt,spring3.2,jetty9
    clean install -U -f camel-sap/pom.xml'
  dependencies:
  - camel-2.21.0-${version.fuse.prefix}

- name: hawtio-2.0.0-${version.fuse.prefix}
  project: jboss-fuse/hawtio
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${hawtio.scmUrl}
    #tag: ${hawtio.tag}
    #buildCommand: ${hawtio.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/hawtio.git
  scmRevision: hawtio-${version.hawtio}
  buildScript: >
    export REG=http://mwnodereg.hosts.mwqe.eng.bos.redhat.com:49183
    mvn  -e -V -B -Pall,spring3.2,enable-schemagen,jetty9,ts.all,release,nochecks,sap,jaxws22,deploy -DnpmRegistryURL=$REG  -Dgpg.skip=true -DnpmDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/dist/npm/
    -DyarnRegistry=$REG  -DskipTests=true -DyarnDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/yarn/dist/
    -DnodeDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/dist/  
    -Dyarn.install.args='--network-concurrency 1 --child-concurrency 1 --no-progress' 
    -Dsass-binary-site=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/node-sass
    deploy
  customPmeParameters:  
    - '-DdependencyOverride.com.fasterxml.jackson.core:*@*='
    - '-DprojectMetaSkip=true'
    - '-DgroovyScripts=org.jboss.fuse.pom-manipulation:yarn-config-groovy:groovy:1.0.4.redhat-1'
    - '-DgroovyManipulationPrecedence=FIRST'
  dependencies:
  - camel-2.21.0-${version.fuse.prefix}
  - karaf-4.2.0-${version.fuse.prefix}

- name: hawtio-online-1.0.0-${version.fuse.prefix}
  project: hawtio/hawtio-online
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${hawtio-online.scmUrl}
    #tag: ${hawtio-online.tag}
    #buildCommand: ${hawtio-online.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/hawtio/hawtio-online.git
  scmRevision: hawtio-online-${version.hawtio.online}
  buildScript: >
    export REG=http://mwnodereg.hosts.mwqe.eng.bos.redhat.com:49183 
    mvn -e -V -B -DskipTests -DfailIfNoTests=false
    -Dtest=false -DnpmRegistryURL=$REG -DnpmDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/dist/npm/
    -DyarnRegistry=$REG -DskipTests=true -DyarnDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/yarn/dist/
    -DnodeDownloadRoot=http://download-node-02.eng.bos.redhat.com/rcm-guest/staging/fuse/npm/dist/
    -Dyarn.install.args='--network-concurrency 1 --child-concurrency 1 --no-progress'
    clean deploy
  customPmeParameters:
    - '-DprojectMetaSkip=true'
  dependencies:
  - hawtio-2.0.0-${version.fuse.prefix}

- name: fuse-karaf-${version.fuse.prefix}
  project: jboss-fuse/fuse-karaf
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/fuse-karaf.git
    #internalScmUrl: ${fuse-karaf.scmUrl}
    #tag: ${fuse-karaf.tag}
    #buildCommand: ${fuse-karaf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/fuse-karaf.git
  scmRevision: fuse-karaf-${version.bom.fuse}
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Psap
    clean deploy '
  dependencies:
  - fuse-components-${version.fuse.prefix}
  - karaf-4.2.0-${version.fuse.prefix}
  - hawtio-2.0.0-${version.fuse.prefix}
  - camel-2.21.0-${version.fuse.prefix}

- name: kubernetes-client-3.0.3-${version.fuse.prefix}
  project: fabric8io/kubernetes-client
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/camel.git
    #internalScmUrl: ${kubernetes-client.scmUrl}
    #tag: ${kubernetes-client.tag}
    #buildCommand: ${kubernetes-client.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-kubernetes-client.git
  scmRevision: kubernetes-client-${version.kubernetes.client}
  dependencies:
  - kubernetes-model-2.0.9-${version.fuse.prefix}


- name: spring-cloud-kubernetes-0.1.6-${version.fuse.prefix}
  project: fabric8io/spring-cloud-kubernetes
    #externalScmUrl: git+https://code.engineering.redhat.com/gerrit/jboss-fuse/spring-cloud-kubernetes.git
    #internalScmUrl: ${spring-cloud-kubernetes.scmUrl}
    #tag: ${spring-cloud-kubernetes.tag}
    #buildCommand: ${spring-cloud-kubernetes.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-spring-cloud-kubernetes.git
  scmRevision: spring-cloud-kubernetes-${version.spring-cloud-kubernetes}
  dependencies:
  - kubernetes-client-3.0.3-${version.fuse.prefix}

- name: docker-maven-plugin-0.23.0-${version.fuse.prefix}
  project: fabric8io/docker-maven-plugin
    #internalScmUrl: ${docker-maven-plugin.scmUrl}
    #tag: ${docker-maven-plugin.tag}
    #buildCommand: ${docker-maven-plugin.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-docker-maven-plugin.git
  scmRevision: docker-maven-plugin-${docker.maven.plugin.version}

- name: fabric8-maven-plugin-3.5.33-${version.fuse.prefix}
  project: fabric8io/fabric8-maven-plugin
    #internalScmUrl: ${fabric8-maven-plugin.scmUrl}
    #tag: ${fabric8-maven-plugin.tag}
    #buildCommand: ${fabric8-maven-plugin.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-fabric8-maven-plugin.git
  scmRevision: fabric8-maven-plugin-${version.fabric8.maven.plugin}
  dependencies:
  - fabric8v2-3.0.11-${version.fuse.prefix} 

- name: fuse-patch-3.0.0-${version.fuse.prefix}
  project: jboss-fuse/fuse-patch
    #internalScmUrl: ${fuse-patch.scmUrl}
    #tag: ${fuse-patch.tag}
    #buildCommand: ${fuse-patch.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/fuse-patch.git
  scmRevision: fuse-patch-${version.fuse.patch}

- name: wildfly-camel-5.1.0-${version.fuse.prefix}
  project: jboss-fuse/wildfly-camel
    #internalScmUrl: ${wildfly-camel.scmUrl}
    #tag: ${wildfly-camel.tag}
    #buildCommand: ${wildfly-camel.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/wildfly-camel.git
  scmRevision: wildfly-camel-${version.bom.wildfly.camel}
  dependencies:
  - fuse-components-${version.fuse.prefix}

- name: wildfly-camel-examples-5.1.0-${version.fuse.prefix}
  project: wildfly-extras/wildfly-camel-examples
    #internalScmUrl: ${wildfly-camel-examples.scmUrl}
    #tag: ${wildfly-camel-examples.tag}
    #buildCommand: ${wildfly-camel-examples.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/wildfly-extras/wildfly-camel-examples.git
  scmRevision: wildfly-camel-examples-${version.wildfly.camel.examples}
  dependencies:
  - wildfly-camel-5.1.0-${version.fuse.prefix}

- name: fuse-eap-${version.fuse.prefix}
    #internalScmUrl: ${fuse-eap.scmUrl}
    #tag: ${fuse-eap.tag}
    #buildCommand: ${fuse-eap.buildCommand}
  project: jboss-fuse/fuse-eap
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/fuse-eap.git
  scmRevision: fuse-eap-${version.fuse.eap}
  dependencies:
  - wildfly-camel-examples-5.1.0-${version.fuse.prefix}

- name: redhat-fuse-${version.fuse.prefix}
  project: jboss-fuse/redhat-fuse
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/redhat-fuse.git
  scmRevision: redhat-fuse-${fuse-bom.version}
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -P clean
    deploy -DskipClean'
  dependencies:
  - fuse-karaf-${version.fuse.prefix}
  - fuse-eap-${version.fuse.prefix}
  - fabric8-maven-plugin-3.5.33-${version.fuse.prefix}

- name: ipaas-quickstarts-2.2.0-${version.fuse.prefix}
  project: fabric8io/ipaas-quickstarts
    #internalScmUrl : ${ipaas-quickstarts.scmUrl}
    #tag: ${ipaas-quickstarts.tag}
    #buildCommand: ${ipaas-quickstarts.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-ipaas-quickstarts.git
  scmRevision: ipaas-quickstarts-${version.ipaas.quickstarts}
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -P clean
    deploy -Dquickstart.git.repos=repolist.txt'
  dependencies:
  - fabric8v2-3.0.11-${version.fuse.prefix} 

- name: fabric8v2-3.0.11-${version.fuse.prefix}
  project: jboss-fuse/fabric8
    #internalScmUrl: ${fabric8.scmUrl}
    #tag: ${fabric8.tag}
    #buildCommand: ${fabric8.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/fabric8io-fabric8.git
  scmRevision: fabric8v2-${version.fabric8}
  dependencies:
  - docker-maven-plugin-0.23.0-${version.fuse.prefix}
  - spring-cloud-kubernetes-0.1.6-${version.fuse.prefix}

- name: cxf-xjc-utils-3.1.1-${version.fuse.prefix}
  project: jboss-fuse/cxf-xjc-utils
    #internalScmUrl: ${cxf-xjc-utils.scmUrl}
    #tag: ${cxf-xjc-utils.tag}
    #buildCommand: ${cxf-xjc-utils.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf-xjc-utils.git
  buildScript: >
    mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false 
    -Dcheckstyle.skip=true clean deploy
  scmRevision: cxf-xjc-utils-${version.cxf.xjc-utils}

- name: hawtio-integration-1.0.0-${version.fuse.prefix}
  project: jboss-fuse/hawtio-integration
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/hawtio-integration.git
  buildScript: mvn clean deploy
  scmRevision: hawtio-integration-${version.hawtio.integration}

- name: kubernetes-model-2.0.9-${version.fuse.prefix}
  project: jboss-fuse/kubernetes-model
    #internalScmUrl: ${kubernetes-model.scmUrl}
    #tag: ${kubernetes-model.tag}
    #buildCommand: ${kubernetes-model.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/kubernetes-model.git
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -P clean
    install '
  scmRevision: kubernetes-model-${version.kubernetes.model}

#- name: application-templates-2.1-${version.fuse.prefix}
#  project: jboss-fuse/application-templates
#  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/application-templates.git
#  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -P clean
#    install '
#  scmRevision: application-templates-${version.application.templates}

outputPrefixes:
  releaseFile: fuse-test
  releaseDir: fuse-test
flow:
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
